<?php

/**
 * Created by PhpStorm.
 * User: @QZH
 * Date: 2018/12/19
 * Time: 15:00
 */
namespace app\base\command;
use app\index\model\User;
use lib\Tpredis;
use think\console\Command;
use think\console\Input;
use think\console\Output;
use think\Db;
use think\facade\Config;
use think\session\driver\Redis;

class Mikkle extends Command
{
    protected $sleep = 2;
    protected function configure()
    {
        //parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('mikkle')->setDescription('this is mikkle\'s command');
    }
    protected function execute(Input $input, Output $output)
    {

        while (true){
            $output->writeln($this->checkDo());
            sleep($this->sleep);
        }
    }
    protected function checkDo()
    {

        $redis = Tpredis::getRedisInstance();
        $redis->setOption();
        $redis->psubscribe(['__keyevent@'.'15'.'__:expired'],function($redis, $pattern, $channel, $msg){
            echo "Pattern: $pattern\n";
            echo "Channel: $channel\n";
            echo "Payload: $msg\n\n";
            $list = explode(':',$msg);
            $order_sn = isset($list[0])?$list[0]:'0';
            Db::name('orders')->where(['order_sn'=>$order_sn,'status'=>0])->update(['status'=>2,'update_time'=>time()]);

        });


    }
    public function keyCallback($redis, $pattern, $channel, $msg)
    {

        echo "Pattern: $pattern\n";
        echo "Channel: $channel\n";
        echo "Payload: $msg\n\n";
        $list = explode(':',$msg);
        $order_sn = isset($list[0])?$list[0]:'0';
        return Db::name('orders')->where(['order_sn'=>"'$order_sn'",'status'=>0])->update(['status'=>2]);

    }
}