<?php
/**
 * Created by PhpStorm.
 * User: @QZH
 * Date: 2019/1/11
 * Time: 23:19
 */

namespace app\base\command;


use think\console\Command;
use think\console\Input;
use think\console\Output;

class Swoole extends Command
{
    protected function configure()
    {
        //parent::configure(); // TODO: Change the autogenerated stub
        $this->setName('swoole')->setDescription('this is swoole\'s command');
    }
    protected function execute(Input $input, Output $output)
    {
        $serv = new \swoole_server('127.0.0.1',9501);
        $serv->on('connect',function ($serv,$fd){
            echo "Client: Connect.\n";
        });
        $serv->set(array(
            'reactor_num' => 2, //reactor thread num
            'worker_num' => 4,    //worker process num
            'backlog' => 128,   //listen backlog
            'max_request' => 50,
            'dispatch_mode' => 1,
        ));
        $serv->on('receive', function ($serv, $fd, $from_id, $data) {
            $serv->send($fd, "Server: ".$data);
        });
        $serv->on('close', function ($serv, $fd) {
            echo "Client: Close.\n";
        });
        $serv->start();
        //$output->comment(json_encode($swoole));
    }
}